### ISSUE TITLE
UTC time when using geo coordinates

### ISSUE THREAD

**Issue by setaur** [kevinboone/solunar_cmdline#2]
Hey thank you for your software!

When I run solunar with location as a city, it shows time in local time format. But, when I'm using geographical coordinates, it shows time in utc, even without --utc parameter:

```
$ solunar --city Warsaw
Selected city Europe/Warsaw
Using location 52:15N,021:00E
Date/time Tue Dec 29 17:12:42 2015 local

Today
                          Date: Tuesday 29 December 2015

Sun
                       Sunrise: 07:45
                        Sunset: 15:28

Moon
                    Moon phase: 0.64 waning gibbous
                      Moonrise: 20:20
                       Moonset: 09:48

$ solunar --latlong +5213+02100
Using location 52:13N,021:00E
Date/time Tue Dec 29 17:17:23 2015 local

Today
                          Date: Tuesday 29 December 2015

Sun
                       Sunrise: 06:45
                        Sunset: 14:28

Moon
                    Moon phase: 0.64 waning gibbous
                      Moonrise: 19:20
                       Moonset: 08:48
```

**Comment by kevinboone** [comment]
Hi

I believe this is the expected behaviour. If you specify a geographical 
location, then the program has no straightforward way to know which 
timezone it is in. In your example, you're picking the latitude and 
longitude of a known city, but what should the program do if the 
coordinates do not match a particular city? I did consider implementing 
a feature where the program would try to locate the nearest city to the 
specified coordinates and use that as the timezone, but I suspect that 
would produces weird results for locations near timezone boundaries.

Your comments are welcome.

Best wishes
Kevin

**Comment by setaur** [comment]
Hi!
Maybe I didn't picture my problem clear. I think that if you don't use --utc switch, then all time should be displayed in local format, and by local I mean timezone set in user computer, not local timezone in that particular geographical point (right - "local" doesn't fit in that sentence very well). So when I want i.e. to check sunrise time in my city (or any other city in the world), I don't have to convert time zones from UTC to local in Poland, since my computer is in Poland and runs by Polish local time. Is that possible in your program?

Cheers
setaur

**Comment by kevinboone** [comment]
Hi

So, if I understand correctly, you want the program to be able to 
display the time in (say) Warsaw when the sun sets in (say) Paris?

Best wishes
Kevin

**Comment by setaur** [comment]
That is correct. So if I would want to get UTC time, I would use --utc parameter. Otherwise I think that time should be displayed in the same timezone which is set on users computer. Isn't it more consistent approach? 

Best wishes
setaur

**Comment by kevinboone** [comment]
Hi

For my purposes, I either want to know the times of sunrise/set in the 
location's own timezone, or in UTC. If I have the time in UTC I can 
easily convert to some other location. If I display system-relative 
times for locations other than my own, then that gives me an extra 
conversion job to get to the local time, which is more complicated if 
daylight savings time is involved, especially if the two timezones in 
question have different DST policies.

However, I can see that it might be nice to be able to specify the 
coordinates of a particular city that is not in the database, but which 
I know are in my local timezone because (for example) the database is 
incomplete. More generally, it might be nice to be able to specify that 
the times should be displayed relative to some other city's timezone. So 
if I know that the city is in the same time as Warsaw, for example, I 
could say:

solunar --latlong XXXXYYYY --timezone warsaw

Or I could just add an option to force the time display to the system 
local time

solunar --latlong XXXXYYYY --local

I guess I would have to think about how the --timezone, --local, and 
--utc options interacted with one another, and which should be the 
default in particular situations.

To be honest, I don't think I would find these facilities very useful, 
but they are easy enough to add (if that's the kind of thing you had in 
mind).

Best wishes
Kevin

**Comment by setaur** [comment]
That would be great. Any of yours solutions would work good for me. 
You know, I just wanted to have simple command to check sunrise and sunset time of my current place (which isn't in that city list) in my local time without additional computing.
Thank you for your effort.

Best wishes
setaur

**Comment by kevinboone** [comment]
Hi

I have made a first attempt at adding a "--syslocal" switch to solunar, 
which should display times at the location of the running system. I have 
also changed some of the output so that the word "syslocal" is used 
rather than "local" when the time is system local. I would prefer to use 
the term "local" to mean specifically "local time at the selected city".

I hope this helps you. If it does, I would be grateful if you could test 
it -- it was much more difficult to implement than I thought, and I'm 
not sure I have dealt with every possible problem.

Best wishes
Kevin

**Comment by setaur** [comment]
Thank you for your effort. But it appears that this option isn't working properly. I marked with ASCII arrows where I think something is wrong.
First with option --city : solunar displays correct "syslocal" time:

```
$ solunar --city Warsaw
Selected city Europe/Warsaw
Using location 52:15N,021:00E
Date/time Sun Jan 10 01:11:30 2016 local <===SYSLOCAL-OK

Today
                          Date: Sunday 10 January 2016

Sun
                       Sunrise: 07:42  <===SYSLOCAL-OK
                        Sunset: 15:42  <===SYSLOCAL-OK

Moon
                    Moon phase: 1.00 new
                      Moonrise: 07:25  <===SYSLOCAL-OK
                       Moonset: 16:41  <===SYSLOCAL-OK
```

Only with --latlong option (coordinates of Warsaw): solunar displays syslocal current time and UTC time for Sun and Moon data (I think it should be consistent and show time in the same time zone - only syslocal or only UTC)

```
$ solunar --latlong +5215+02100
Using location 52:15N,021:00E
Date/time Sun Jan 10 01:11:48 2016 syslocal  <===SYSLOCAL

Today
                          Date: Sunday 10 January 2016

Sun
                       Sunrise: 06:42  <===UTC
                        Sunset: 14:42  <===UTC

Moon
                    Moon phase: 1.00 new
                      Moonrise: 06:25  <===UTC
                       Moonset: 15:41  <===UTC
```

With options --latlong and --syslocal: solunar shows syslocal current time, but it displays UTC time for Sun and Moon data, which is incorrect

```
$ solunar --latlong +5215+02100 --syslocal
Using location 52:15N,021:00E
Date/time Sun Jan 10 01:11:58 2016 syslocal <===SYSLOCAL-OK

Today
                          Date: Sunday 10 January 2016

Sun
                       Sunrise: 06:42  <===UTC-WRONG
                        Sunset: 14:42  <===UTC-WRONG

Moon
                    Moon phase: 1.00 new
                      Moonrise: 06:25  <===UTC-WRONG
                       Moonset: 15:41  <===UTC-WRONG
```

With options --latlong and --utc: all is fine except incorrect "syslocal" label in current time section

```
$ solunar --latlong +5215+02100 --utc
Using location 52:15N,021:00E
Date/time Sun Jan 10 00:12:48 2016 syslocal <===[Time is UTC, but there is label "syslocal"]

Today
                          Date: Sunday 10 January 2016

Sun
                       Sunrise: 06:42  <===UTC-OK
                        Sunset: 14:42  <===UTC-OK

Moon
                    Moon phase: 1.00 new
                      Moonrise: 06:25  <===UTC-OK
                       Moonset: 15:41  <===UTC-OK
```

Best wishes
setaur

**Comment by kevinboone** [comment]
Hi

Sorry, this is much more difficult that I thought. The problem is that I 
never made any allowance for working with system-local times, so I 
assumed that the TZ environment variable would always be set to either 
UTC or the timezone of the selected city. But a non-existent value of TZ 
is also allowed, to indicate that the system local time should be used. 
So I've had to go through the code and figure out every place I need to 
unset TZ.

I've uploaded a new version. It seems to work correctly when I set my 
system timezone to Warsaw; but please let me know what you think.

Best wishes
Kevin

**Comment by setaur** [comment]
I did check again and all looks all OK.
Thank you very much for your program! If I find any flaws, I'll let you know.

Best wishes!
setaur

**Comment by kevinboone** [comment]
It occurs to me that solunar has always had a way to output dates in a 
specified timezone, by using the --latlong switch in combination with 
--city. With this combination, the specified latitude and longitude 
override those in the city database, which is then only used for its 
timezone. To be honest, I had forgotten about this feature.

Best wishes
Kevin

**Comment by setaur** [comment]
Hmm, I didn't thought about that combination. It would work for me also, but I think that new option you added is still better (because you don't have to switch the city name, if you move abroad). 
BTW. there is no description of "--syslocal" parameter in programs help.

Best wishes!
setaur

**Comment by kevinboone** [comment]
Hi. The latest revision (pushed this morning) should have --syslocal in the
help. Please let me know if that isn't what you see. Best wishes, Kevin

**Comment by setaur** [comment]
I checked it and it looks all right. 

Best wishes
setaur

**Comment by rupertapplin** [comment]
Hi, 
Just found this, great little application - been perfect for what I'm needing, though I'm wondering if there is an issue with the output of the moon set time - I'm using the switches as you suggested above:

./solunar -l -41.2889,174,7772 -c auckland

so as to use my location (Wellington) but forcing the timezone local (by using Auckland to force this) the output is perfect for everything - excepting moonset, as shown here:

Selected city Pacific/Auckland
Overriding city location with specified lat/long
Using location 41:17S,174:00E
Date/time Wed Jan 20 17:39:58 2016 local

Today
                          Date: Wednesday 20 January 2016

Sun
                       Sunrise: 06:14
                        Sunset: 20:53

Moon
                    Moon phase: 0.37 waxing gibbous
                      Moonrise: 17:11
                       Moonset: 03:25

According to our Met Service (and other online resources) moonrise should be 17:07 (so close enough) and moonset should be 02:35 - but out by a reasonable margin - I thought this might be day light savings, however it's the same issue for the 1st July

Have been using this website for checking..

http://www.timeanddate.com/moon/new-zealand/wellington?month=7&year=2016

Thoughts?
Cheers
Rupert

**Comment by kevinboone** [comment]
Hi

Thanks for pointing this out. I confess that you aren't the first person 
to raise this problem, which seems to concern timezones in the general 
region of UTC+12. I'm pretty sure that the incorrect moonset time you 
see is the time the moon set from "yesterday," relative to your 
timezone. Perhaps you would be kind enough to check that, against 
whatever reliable source you use.

My program struggles with timezones where the time is not merely offset 
from UTC (as nearly all timezones are), but offset in such a way that we 
might report a different day. Although I know what causes the problem 
(or, at least think I do), I'm far from certain how to fix it without 
causing problems elsewhere. I suppose at a minimum I could start by 
printing the dates on the moon times as well as the times; that way at 
least it's obvious whether it's today or not.

Please bear with me; I need to give this matter some thought.

Best wishes
Kevin

**Comment by rupertapplin** [comment]
Hi,
Thanks for the quick reply. Does look like you're out by a day with regard
to moonrise - even when both rise and set are , I notice though that your
day of the year shows for the 20th Jan as Day 19 - would this account for
it some how?
Cheers
Rupert

**Comment by kevinboone** [comment]
Hi

I think the problem lies in working out where the day starts, in time 
zones 12 hours or more ahead of UTC. Presumably
there would be a similar problem (in the other direction, so to speak) 
for time zones more than 12 hours behind UTC.

I've tidied up the time zone conversions in those parts of the program 
that work out when the day starts and ends -- I hope this will help. I 
have uploaded a new version to github. I would be interested to know 
whether the situation is improved.

Best wishes
Kevin

**Comment by rupertapplin** [comment]
Hi,
Looking good - working fine for me now - for both dates during daylight savings and when not. 
Much appreciated!
Cheers
Rupert

**Comment by kevinboone** [comment]
No further complaints -- assuming issue can be closed.
